//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joindernoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaElim { get; set; }
        public Nullable<int> IdSubcategoria { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdBlog { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> NumView { get; set; }
    }
}
